name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: '20.17.0'

      - name: Install dependencies
        working-directory: ./spotify-timer-frontend  # Set correct folder
        run: npm install

      - name: Build the project
        working-directory: ./spotify-timer-frontend  # Set correct folder

        run: ng build --output-path=dist/my-angular-app --base-href /my-angular-app/

      - name: Deploy to GitHub Pages
        working-directory: ./spotify-timer-frontend  # Set correct folder
        run: npx angular-cli-ghpages --dir=dist/my-angular-app
