name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.17.0'
      - name: Change directory to frontend (if package.json is inside a subfolder)
        run: cd ./spotify-timer-frontend
      - run: npm install
      - run: npm run lint